### PR TITLE
Iron To Diamond Chest Upgrade

### PR DESCRIPTION
**Pull request by hugeblank**
Adds an iron chest to diamond chest upgrade item, bringing parity to the chest non-item upgrade path.

### CODE REVIEW

**Comment by hugeblank** [comment]
... maybe `.cache` should be added to the .gitignore

**Comment by Lemmmy** [comment]
I believe it's intended to not be .gitignore'd, but it is added to .gitattributes

**Comment by Lemmmy** [comment]
Thanks for the fantastic PR! Will test shortly. I see there is a texture for the iron->diamond shulker upgrade, is there meant to be a recipe for this too?

**Comment by hugeblank** [comment]
> I see there is a texture for the iron->diamond shulker upgrade, is there meant to be a recipe for this too?

Bah! Knew I forgot something. Will add that now.

**Comment by hugeblank** [comment]
Should be ready for testing now!

**Comment by Lemmmy** [comment]
Thanks for working on this!

**Pull request merged**
