### PR TITLE
Grass types can be turned into farmland and paths

### LINKED ISSUE #42: Colored grass can not be turned into farmland
Colored grass can not be turned into farmland when using a hoe. If you try and right click the grass, nothing happens.

### PR DESCRIPTION
**Pull request by penguinencounter**
Fixes #42.

The goodies grass types can be turned into farmland (use a hoe item) or dirt paths (use a shovel item).

### CODE REVIEW

**Comment by penguinencounter** [comment]
Would it be possible to gitignore the cache folder? I had to do a conflict resolution pass on it...

**Comment by Lemmmy** [comment]
Thanks for the PR!

Fabric has a registry for tillable blocks and pathable blocks - [TillableBlockRegistry](https://github.com/FabricMC/fabric/blob/1.20.1/fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/TillableBlockRegistry.java) and FlattenableBlockRegistry. We already use the FlattenableBlockRegistry for paths:

https://github.com/SwitchCraftCC/sc-goodies/blob/3d03a7364dfc3e543bc34dc8f5ed2b1c7b04a5b9/src/main/kotlin/io/sc3/goodies/Registration.kt#L164-L166

Did you test if using a shovel to make path already worked without your PR? It should do - if not, that is a bug. For hoe items, please use the Fabric registry (in the same place in Registration as above) instead of a mixin so we can avoid potential conflict with the Fabric API.

> Would it be possible to gitignore the cache folder? I had to do a conflict resolution pass on it...

The Fabric example mod doesn't gitignore the .cache folder, so we trust their decision not to.

**Comment by penguinencounter** [comment]
oops! did not know it would do that
(force-pushed a reset to 1.20.1)

**Comment by Lemmmy** [comment]
Brilliant, thank you!

**Pull request merged**
